name: AWS Deployment

on:
  push:
    branches: [ master ]

# A worklow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: git push to AWS
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        dokku-host: ${{ secrets.DOKKU_HOST }}
        app-name: ${{ secrets.DOKKU_APP_NAME }}
